### PR TITLE
Add instructions for Windows compile

### PR DESCRIPTION
**Pull request by whophil**
Based on discussions with Daniel Houck.

### CODE REVIEW

**Review by kmruehl — APPROVED** [review]
Looks good to me and was tested by Dan Houck

**Comment by kmruehl** [comment]
@whophil I am pushing a typo fix to this branch and then will merge

**Comment by kmruehl** [comment]
@whophil I have a question about `bin` and `build`. Right now `bin` is empty since precompiled executables are not provided for CACTUS. Should we remove the `bin` directory from the repository and update `README.md` and `compile.md` to reflect using the `build` directory? Specifically updating `PATH=$PATH:../../build/ pytest ./runreg.py` to run tests?

**Comment by kmruehl** [comment]
@whophil on second thought, it seems like this another path issue with Windows. Is `cactus.exe` supposed to be copied into the `\bin` directory once it's compiled? It looks like it supposed to happen in `CMakeLists.txt`. If so, that's not happening on Windows. 

This is actually related to https://github.com/SNL-WaterPower/CACTUS/pull/22 and not a doc issue.

**Comment by whophil** [comment]
@kmruehl it is indeed a doc issue, the correct `make` command is `make install`.
See https://github.com/SNL-WaterPower/CACTUS/pull/23

**Pull request merged**
