### PR TITLE
Build with cmake

### PR DESCRIPTION
**Pull request by whophil**
The previous build system of platform-specific Makefiles requiring manual modification was pretty hairy. Here is a new build setup which uses CMake, with the following advantages:
- A single configuration file (`CMakeLists.txt`) for all platforms and options
- Automatic detection of paths for OpenMP, LAPACK/BLAS
- Automated dependency resolution within Fortran sources/modules - no more need to specify the compile order by hand

This will require some updates to the compile instructions, but those will conflict with #17. So let's merge that one first, and then I'll fix this PR up.

### CODE REVIEW

**Comment by whophil** [comment]
Added some changes to address #6 (PGI compiler problems) and #11 (Don't fail on missing git).

Building with the PGI compiler is not tested in Travis. It's certainly possible but I'm not sure it's worth doing.

**Review by petebachant — APPROVED** [review]
I'm no CMake expert but this seems like a big improvement.

**Review by kmruehl — COMMENTED** [review]
@petebachant same, and I agree. Having one Makefile, instead of one for each platform, seems like a huge improvement to me.

**Comment by kmruehl** [comment]
@jcokemurray can you review and approve this PR?

**Comment by whophil** [comment]
Rebased onto the tip of `dev` to resolve conflicts. I removed the outdated Windows install instructions. If somebody wishes they can update `doc/compile.md` with Windows-specific instructions.

**Comment by jcokemurray** [comment]
Works for me. Cmake would definitely be an improvement over the manual Makefile approach...

**Review by jcokemurray — APPROVED** [review]

**Comment by kmruehl** [comment]
@jcokemurray thanks for reviewing. @whophil merging this PR now.

**Pull request merged**
